export const DataStoryFr =[
  {
      srcstr1:'./images/story/story1.jpg',
      alt1:'str-1',
      srcavtstr1:'./images/avt/1-avt.jpg',
      alt2:'1-avt',
      name:'John'
},{
      srcstr1:'./images/story/story2.jpg',
      alt1:'str-2',
      srcavtstr1:'./images/avt/2-avt.jpg',
      alt2:'2-avt',
      name:'Anna'
},{
      srcstr1:'./images/story/story3.jpg',
      alt1:'str-3',
      srcavtstr1:'./images/avt/3-avt.jpg',
      alt2:'3-avt',
      name:'Sam'
},{
      srcstr1:'./images/story/story4.jpg',
      alt1:'str-4',
      srcavtstr1:'./images/avt/4-avt-str.jpg',
      alt2:'4-avt',
      name:'Jane'
},{
      srcstr1:'./images/story/story5.jpg',
      alt1:'str-5',
      srcavtstr1:'./images/avt/5-avt.jpg',
      alt2:'5-avt',
      name:'Khanh'
},{
      srcstr1:'./images/story/story6.jpg',
      alt1:'str-6',
      srcavtstr1:'./images/avt/6-avt.jpg',
      alt2:'6-avt',
      name:'Linh Chi'
}
]