export const DataPost =[
    {
        id:'p1',
        gr:'true',
        src_avt_gr:'./images/avt/avt-gr-1.png',
        alt_avt_gr:'gr-1',
        src_avt:'./images/avt/avt-post-3.jpg',
        alt_avt:'avt',
        name_gr:'TỰ ÔN TOEIC CẤP TỐC 2023',
        name_p:'Nguyễn LiLa',
        time:'3 days ago',
        ct_type:'sg-pic',
        cap:'Khởi động ngày mới nhé các bạn!',
        hastag:'#tienganhthayquy #so1toeiconline #toeic #toeiconline',
        src_pic_content1:'./images/ct-post/pic-post-3.jpg',
        numoflike:'Đức Thịnh and 243 others',
        numofcmt:'8',
        numofshare:'1',
    },{
        id:'p2',
        gr:'false',
        src_avt_gr:'none',
        alt_avt_gr:'none',
        src_avt:'./images/avt/1-avt.jpg',
        alt_avt:'1-avt',
        name_gr:'none',
        name_p:'Linh Chi',
        time:'2 hrs ago',
        ct_type:'pic_w_vid',
        cap:'Góc khoe dáng mèo ngủ, em trước:',
        src_vid:'./Vids/cat-video.mp4',
        numoflike:'Linh Chi and 10k others',
        numofcmt:'121',
        numofshare:'32',
    },{
        id:'p3',
        gr:'false',
        src_avt_gr:'none',
        alt_avt_gr:'none',
        src_avt:'./images/avt/4-avt.webp',
        alt_avt:'4-avt',
        name_gr:'none',
        name_p:'Hồ Đức Hoàng',
        time:'2 weeks ago',
        ct_type:'album',
        cap:'Yuji như này đủ làm thịt Sukuna chưa 🐧',
        hastag:'#sach',
        src_pic_content1:'./images/ct-post/img-1-album.jpg',
        src_pic_content2:'./images/ct-post/img-2-album.jpg',
        src_pic_content3:'./images/ct-post/img-3-album.jpg',
        src_pic_content4:'./images/ct-post/img-4-album.jpg',
        src_pic_content5:'./images/ct-post/img-5-album.jpg',
        num_p:'18',
        numoflike:'537',
        numofcmt:'43',
        numofshare:'36',
    },{
        id:'p4',
        gr:'false',
        src_avt_gr:'none',
        alt_avt_gr:'none',
        src_avt:'./images/avt/5-avt.jpg',
        alt_avt:'5-avt',
        name_gr:'none',
        name_p:'Anonymous paticipant ',
        time:'4 days ago',
        ct_type:'vote',
        cap:'Định làm giải cho anh em sv cho tui biết mọi người ở đâu đi ạ',
        name_choice_1:'NEU',percent_1:'14%',
        name_choice_2:'KHTN HCM',percent_2:'26%',Added_by_2:'Nguyễn Đình Thiên Phúc ',
        name_choice_3:'TDT',percent_3:'3%',Added_by_3:'Bóng Đá Phủi',
        name_choice_4:'FPTU fuda',percent_4:'3%',Added_by_4:'Phan Nhân Tuấn Kiệt ',
        name_choice_5:'HCMUET',percent_5:'32%',Added_by_5:'Ngô Thế Quyền',
        numoflike:'133',
        numofcmt:'11',
        numofshare:'3',
    },{
        id:'p5',
        gr:'false',
        src_avt_gr:'none',
        alt_avt_gr:'none',
        src_avt:'./images/avt/2-avt.jpg',
        alt_avt:'2-avt',
        name_gr:'none',
        name_p:'Giang Tran Vu',
        time:'10 hrs ago',
        ct_type:'word',
        para1:'Anh em cho hỏi có thể đọc Jujutsu Kaisen ở đâu với chất lượng dịch tốt hơn được ko?',
        para2:'Ko biết team nào dịch bộ này, đọc rất khó chịu, nhiều câu lủng củng, cụt ngủn, ko ăn khớp với nhau, tên skill nghe cũng rất vô nghĩa hoặc khó hiểu',
        numoflike:'12',
        numofcmt:'5',
        numofshare:'1',
    }
]